#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FrontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           BackRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BackLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driveControl()
{
	motor[FrontLeft] = vexRT(Ch3);
	motor[FrontRight] = vexRT(Ch4);
	motor[BackLeft] = vexRT(Ch3);
	motor[BackRight] = vexRT(Ch4);
	
	//Dev was here
}
//justin was here
