#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FrontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           gear1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           gear2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           gear3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           gear4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BackRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BackLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



void driveControl()
{
	motor[FrontLeft] = vexRT(Ch3);
	motor[FrontRight] = vexRT(Ch4);
	motor[BackLeft] = vexRT(Ch3);
	motor[BackRight] = vexRT(Ch4);
}
